### ISSUE TITLE
[cli] Handle unknown command

### ISSUE THREAD

**Issue by kevingimbel** [lucapette/fakedata#9]
Hey, I just discovered this project and gave it a try. Naturally I tried to run `fakedata help` because most Go programs I used have this as a command; `fakedata` without an argument however just outputs 10 empty lines which is an odd behaviour IMO. 

I looked at the code and this happens because the `limit` flag defaults to 10 and [the fakedata generation runs](https://github.com/lucapette/fakedata/blob/master/cmd/fakedata.go#L94-L96)  with the default seperator (space), so 10 "empty datasets" are printed. 

I think it would be a good idea to have `Unknown command: X` message for unknown commands. I see that you [check for empty args here](https://github.com/lucapette/fakedata/blob/master/cmd/fakedata.go#L84-L87).

If you want to I could give this a shot, tho I am quite new to Go. If it's intended behaviour I guess this issue can just be closed. 😃

**Comment by lucapette** [comment]
Thank you very much for trying it out!

As I was the only user of the project so far, I'm sure there are even odder things  happening. So your feedback is *gold* to me.

About the specific issue:

- I don't particularly like the idea of adding subcommands because I think it can become cumbersome over time to distinguish subcommands from generators. Moreover, I'm not sure the tool will ever need other subcommands (that _ever_ is a long shot.. but I can't come up with anything meaningful)
- I agree 100% that fakedata has to say something when it can't generate anything. I'd say a message along the lines of `Unknown generator: help. Please check fakedata --generators for more information about available generators` (using the specific example) would fit better.

I'm basically assuming we don't change the current CLI interface, meaning no subcommands + options via `-` o `--` but we fix the "bug" you found.

If you're up for it, I'd _love_ to help you landing a contribution. The fact you're quite new to Go is one reason more for me to be excited to help so I wouldn't worry about it :)

**Comment by kevingimbel** [comment]
> I don't particularly like the idea of adding subcommands because I think it can become cumbersome over time to distinguish subcommands from generators.

I have to agree with you on this. After playing around a bit more I found it very handy to specify whatever generators I needed after each other, e.g. `fakedata --format csv name email country state` - it's quite easy to play around with data this way. 

I'll see if I get the time tonight to work on it and then I'll open a pull request.

**Comment by lucapette** [comment]
@kevingimbel thank you for giving it a try! You made my day :)

**Comment by kevingimbel** [comment]
@lucapette YOU made my day! You're very welcoming - it's always a big step to offer contributions, especially since I'm new to Go. 😄

**Comment by lucapette** [comment]
Done in #10 🎉
